---
- name: copy ssl
  copy:
    src: /opt/ssl
    dest: /opt/

- name: download kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl
    dest: /usr/bin/kubectl
    mode: 0755

- name: check kubectl version
  register: kubectl_version
  shell: kubectl version --client

- debug: var=kubectl_version.stdout_lines

- name: Get IP master
  shell: host {{name_master}} | awk '{print $4}'
  register: "ip_master_reg"
- debug: var="ip_master_reg.stdout"
- name: variable ip
  set_fact:
    ip_master: "{{ ip_master_reg.stdout }}"

- name: Generate a kubeconfig file suitable for authenticating as the admin user
  shell: kubectl config set-cluster kubernetes --certificate-authority=ca.pem --embed-certs=true --server=https://{{ip_master}}:6443
  args:
    chdir: /opt/ssl/

- shell: kubectl config set-credentials admin --client-certificate=admin.pem --client-key=admin-key.pem
  args:
    chdir: /opt/ssl

- shell: kubectl config set-context kubernetes --cluster=kubernetes --user=admin

- shell: kubectl config use-context kubernetes
