---
- name: install nginx
  yum:
    name: nginx
    state: present

- name: create dir
  file:
    path: /etc/nginx/stream-enabled
    state: directory

- name: create nginx config
  template:
    src: kubernetes-nginx
    dest: /etc/nginx/stream-enabled/kubernetes

- name: create nginx config 2
  lineinfile:
    path: /etc/nginx/nginx.conf
    line: include /etc/nginx/stream-enabled/*;

- name: enable nginx and start
  service:
    name: nginx
    enabled: true
    state: restarted
